### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MariaRamos89** [NoosWare/noos-api-cpp#1]
When I tried to compile I had this error:

```
rapp-api-cpp/noos/cloud/node.tpl:85:53: error: variable 'result' declared with 'auto' type cannot appear in its own initializer
                                   [&](auto reply){ result.object.process(reply); });
```

I'm using g++ version 6.2.0

**Comment by alexge233** [comment]
Did you clone my branch?
Try setting `auto` to `std::string` (this is what it is, the json string reply).

**Comment by MariaRamos89** [comment]
Yes, the branch is correct.
It's not complaining about `reply`, but `result`.
In any case, I tried it (change `auto` to `std::string`) but it's still the same error.
